name: Upload to S3

on:
  push:
    branches:
      - main  # Or any branch you want to trigger on

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://titiresume --exclude ".git/*"
